services:
  db:
    container_name: ${DK_MARIADB_CONTAINER_NAME}
    image: mariadb:10.11
    ports:
      - "${DK_MARIADB_HOST_PORT:-3306}:3306"
    volumes:
      - ./db/mariadb:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE_NAME}
      MARIADB_USER: ${MARIADB_USER_NAME}
      MARIADB_PASSWORD: ${MARIADB_USER_PASSWORD}

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2
    ports:
      - "${PHPMYADMIN_HOST_PORT:-8082}:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${MARIADB_USER_NAME}
      PMA_PASSWORD: ${MARIADB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    depends_on:
      - db