
# REST Client for Visual Studio Code
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# ##########################################
# Authentication API Endpoints
# ##########################################

### REGISTER (POST)
POST http://localhost:7000/api/v1/auth/register
Content-Type: application/json

{
  "username": "lisaSimpson",
  "email": "lisa@springfield.com",
  "password": "123456789",
  "confirmPassword": "123456789"
}


### LOGIN (POST)
POST http://localhost:7000/api/v1/auth/login
Content-Type: application/json

{
  "username": "homerSimpson",
  "password": "12345678"
}

# ------------------------------------------

# ##########################################
# User Management API Endpoints
# ##########################################

### GET ALL USERS (GET)
GET http://localhost:7000/api/v1/user
Content-Type: application/json

### GET USER BY ID (GET)
GET http://localhost:7000/api/v1/user/1
Content-Type: application/json

### UPDATE USER BY ID (PATCH)
PATCH http://localhost:7000/api/v1/user/1
Content-Type: application/json

{
  "username": "homerRompson"
}

# ------------------------------------------


### ACCESS PROTECTED ENDPOINT (GET)
GET http://localhost:7000/api/v1/auth/profile
Authorization: Bearer {{token}}
